package com.keks.plan


// TODO remove parser from all nodes names
package object operations {
  val FILTER = "FILTER"
  val WINDOW = "WINDOW"
  val DEDUPLICATE = "DEDUPLICATE"
  val DISTINCT = "DISTINCT"
  val JOIN = "JOIN"
  val UNION = "UNION"
  val AGGREGATE = "AGGREGATE"
  val COLUMNS_MODIFICATIONS = "COLUMNS_MODIFICATIONS"
  val MAP_TRANSFORMATION = "MAP_TRANSFORMATION"
  val SELECT = "SELECT"
  val SOURCE_TABLE = "SOURCE_TABLE"
  val CREATED_BY_CODE = "CREATED_BY_CODE"
  val CATALOG_SOURCE_TABLE = "CATALOG_SOURCE_TABLE"
  val WITH_TABLE = "WITH_TABLE"
  val TABLE_ALIAS = "TABLE_ALIAS"
  val SKIP_OPERATION = "SKIP_OPERATION"
  val COLUMNS_OPERATION = "COLUMNS"
  val FLATMAP_TRANSFORMATION = "FLATMAP_TRANSFORMATION"
}
